{{- $rootContext := . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mina-standard-daemon.fullname" . }}
  labels:
    {{- include "mina-standard-daemon.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.daemon.role "snarkWorker" }}
  replicas: {{ .Values.daemon.replicas }}
  {{- else }}
  replicas: 1 # we do not support scaling the daemon
  {{- end }}
  {{- with .Values.strategy }}
  strategy: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mina-standard-daemon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mina-standard-daemon.labels" . | nindent 8 }}
        {{- include "mina-standard-daemon.mina-labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mina-standard-daemon.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- $initContainers := .Values.initContainers -}}
        {{- with .Values.extraInitContainers -}}
        {{/*
          Adding extra init containers
        */}}
        {{- $initContainers = concat $initContainers . -}}
        {{- end -}}
        {{- range $initContainers }}
        {{- $context := merge (dict "root" $rootContext) . -}}
        {{- include "mina-standard-daemon.container" $context | nindent 8 }}
        {{- end }}
      containers:
        {{- $containers := list .Values.daemon -}}
        {{- with .Values.daemon.extraContainers -}}
        {{/*
          Adding extra containers
        */}}
        {{- $containers = concat $containers . -}}
        {{- end -}}
        {{- range $containers }}
        {{- $context := merge (dict "root" $rootContext) . -}}
        {{- include "mina-standard-daemon.container" $context | nindent 8 }}
        {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.restartPolicy | default "Always" }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
