{{- $root := . -}}
{{- if .Values.secrets.secrets }}
{{- range .Values.secrets.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  {{- with .secretsAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "mina-standard-daemon.labels" $root | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: {{ .type | default "Opaque" }}
data:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
