name: Validate Helm Templates

on:
  pull_request:
    paths:
      - 'mina-node-orchestrator/**'
      - '.github/workflows/validate-templates.yml'
  push:
    branches:
      - main
    paths:
      - 'mina-node-orchestrator/**'

jobs:
  check-defaults-sync:
    name: Check defaults.yaml Synchronization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: Check defaults.yaml is in sync
        working-directory: mina-node-orchestrator
        run: |
          # Backup current defaults.yaml
          cp environment/defaults.yaml /tmp/defaults.yaml.backup

          # Regenerate defaults.yaml
          ./scripts/merge-roles.sh

          # Compare
          if diff -wB /tmp/defaults.yaml.backup environment/defaults.yaml > /dev/null; then
            echo "✓ defaults.yaml is synchronized with role files"
          else
            echo "✗ defaults.yaml is OUT OF SYNC with role files"
            echo ""
            echo "Please run './scripts/merge-roles.sh' and commit the result"
            echo ""
            echo "Differences:"
            diff -u /tmp/defaults.yaml.backup environment/defaults.yaml | head -30 || true
            exit 1
          fi

  validate-templates:
    name: Validate Templates - ${{ matrix.fixture }}
    runs-on: ubuntu-latest
    needs: check-defaults-sync

    strategy:
      fail-fast: false
      matrix:
        fixture:
          - devnet
          - rust-seeds
          - rust-bps

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run template validation for ${{ matrix.fixture }}
        working-directory: mina-node-orchestrator
        env:
          CONTAINER_CMD: podman
          # Skip defaults.yaml check in CI due to container permission issues
          # This check is still valuable locally for developers
          SKIP_DEFAULTS_CHECK: true
        run: |
          ./scripts/test-templates.sh ${{ matrix.fixture }}

      - name: Upload rendered templates
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rendered-templates-${{ matrix.fixture }}
          path: /tmp/${{ matrix.fixture }}-templates.yaml
          retention-days: 7
          if-no-files-found: ignore

  summary:
    name: Validation Summary
    runs-on: ubuntu-latest
    needs: [check-defaults-sync, validate-templates]
    if: always()

    steps:
      - name: Check results
        run: |
          SYNC_RESULT="${{ needs.check-defaults-sync.result }}"
          TEMPLATES_RESULT="${{ needs.validate-templates.result }}"

          if [ "$SYNC_RESULT" == "success" ] && [ "$TEMPLATES_RESULT" == "success" ]; then
            echo "========================================="
            echo "✅ All validations passed"
            echo "========================================="
            echo ""
            echo "Checks completed:"
            echo "  ✓ defaults.yaml synchronized with role files"
            echo "  ✓ Template rendering for 14 nodes"
            echo ""
            echo "Validated fixtures:"
            echo "  - devnet: 10 nodes (5 roles)"
            echo "  - rust-seeds: 2 nodes (2 roles)"
            echo "  - rust-bps: 2 nodes (1 role)"
            echo ""
            echo "Total: 14 nodes across 9 roles"
            echo "Coverage: 82% of all node role types"
          else
            echo "========================================="
            echo "❌ Validation failed"
            echo "========================================="
            echo ""
            echo "Results:"
            echo "  defaults.yaml sync: $SYNC_RESULT"
            echo "  Template rendering: $TEMPLATES_RESULT"
            echo ""
            echo "Check the logs above for details"
            exit 1
          fi
